twist_mux:
  ros__parameters:
    use_stamped: true # Set to true if using geometry_msgs/TwistStamped messages
    # Example input topics (adjust as needed)
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 10
      joystick  : 
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
      safety  : 
        topic   : cmd_vel_safe
        timeout : 0.5
        priority: 200
      keyboard  : 
        topic   : cmd_vel_key
        timeout : 0.5
        priority: 50
      ctrl : 
        topic   : cmd_vel_ctrl
        timeout : 0.5
        priority: 50